#ifndef __JETT_PLACARD_BACKLIGHT_H
#define __JET_PLACARD_BACKLIGHT_H



#define NUM_JETT_PLACARD_LEDS 8

int JETT_PLACARD_OFFSET = STATION_SELECT_OFFSET + NUM_STATION_SELECT_LEDS;

int JETT_PLACARD_LED_LIST[NUM_JETT_PLACARD_LEDS] = {0,1,2,3,4,5,6,7};

CRGB JETT_PLACARD_LEDS[NUM_JETT_PLACARD_LEDS];

void UpdateJettPlacardBacklightLEDS(int value){
  BackLighting::updateBacklight(value, JETT_PLACARD_LED_LIST,NUM_JETT_PLACARD_LEDS,JETT_PLACARD_LEDS);
    BackLighting::updateLeftLipLEDS(NUM_JETT_PLACARD_LEDS,JETT_PLACARD_OFFSET,JETT_PLACARD_LEDS);
}

#endif