#ifndef __STANDBY_INSTRUMENTS_H
#define __STANDBY_INSTRUMENTS_H



#define NUM_STANDBY_INSTRUMENTS_LEDS 6

int STANDBY_INSTRUMENT_OFFSET = CABIN_PRESSURE_OFFSET + NUM_CABIN_PRESSURE_LEDS;

int STANDBY_INSTRUMENT_LED_LIST[NUM_STANDBY_INSTRUMENTS_LEDS] = {0,1,2,3,4,5};

CRGB STANDBY_INSTRUMENT_LEDS[NUM_STANDBY_INSTRUMENTS_LEDS];

void UpdateStandbyInstrumentBacklightLEDS(int value){
  BackLighting::updateBacklight(value, STANDBY_INSTRUMENT_LED_LIST,NUM_STANDBY_INSTRUMENTS_LEDS,STANDBY_INSTRUMENT_LEDS);
  BackLighting::updateLipLEDS(NUM_STANDBY_INSTRUMENTS_LEDS,STANDBY_INSTRUMENT_OFFSET,STANDBY_INSTRUMENT_LEDS);
}


#endif