#ifndef __VIDEO_RECORDER_BACKLIGHT_H
#define __VIDEO_RECORDER_BACKLIGHT_H



#define NUM_VIDEO_RECORDER_LEDS 16

int VIDEO_RECORDER_OFFSET = NUM_IFEI_LEDS;

int VIDEO_RECORDER_LED_LIST[NUM_VIDEO_RECORDER_LEDS] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15};

CRGB VIDEO_RECORDER_LEDS[NUM_VIDEO_RECORDER_LEDS];

void UpdateVideoRecorderBacklightLEDS(int value){
  BackLighting::updateBacklight(value, VIDEO_RECORDER_LED_LIST,NUM_VIDEO_RECORDER_LEDS,VIDEO_RECORDER_LEDS);
    BackLighting::updateLeftLipLEDS(NUM_VIDEO_RECORDER_LEDS,VIDEO_RECORDER_OFFSET,VIDEO_RECORDER_LEDS);
}


#endif